"""add core service tables

Revision ID: d8c951357bb9
Revises: 643a4fbd24ef
Create Date: 2026-03-18 02:26:04.290274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8c951357bb9'
down_revision: Union[str, Sequence[str], None] = '643a4fbd24ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_title'), 'resources', ['title'], unique=False)
    op.create_table('specialties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specialties_name'), 'specialties', ['name'], unique=True)
    op.create_table('resource_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'segment_index', name='uq_resource_segments_resource_segment')
    )
    op.create_index(op.f('ix_resource_segments_resource_id'), 'resource_segments', ['resource_id'], unique=False)
    op.create_table('search_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_queries_user_id'), 'search_queries', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('user_specialties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.Column('proficiency_level', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'specialty_id', name='uq_user_specialties_user_specialty')
    )
    op.create_index(op.f('ix_user_specialties_specialty_id'), 'user_specialties', ['specialty_id'], unique=False)
    op.create_index(op.f('ix_user_specialties_user_id'), 'user_specialties', ['user_id'], unique=False)
    op.create_table('search_query_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_query_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['search_query_id'], ['search_queries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_query_id', 'resource_id', name='uq_search_query_results_query_resource')
    )
    op.create_index(op.f('ix_search_query_results_resource_id'), 'search_query_results', ['resource_id'], unique=False)
    op.create_index(op.f('ix_search_query_results_search_query_id'), 'search_query_results', ['search_query_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_query_results_search_query_id'), table_name='search_query_results')
    op.drop_index(op.f('ix_search_query_results_resource_id'), table_name='search_query_results')
    op.drop_table('search_query_results')
    op.drop_index(op.f('ix_user_specialties_user_id'), table_name='user_specialties')
    op.drop_index(op.f('ix_user_specialties_specialty_id'), table_name='user_specialties')
    op.drop_table('user_specialties')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_search_queries_user_id'), table_name='search_queries')
    op.drop_table('search_queries')
    op.drop_index(op.f('ix_resource_segments_resource_id'), table_name='resource_segments')
    op.drop_table('resource_segments')
    op.drop_index(op.f('ix_specialties_name'), table_name='specialties')
    op.drop_table('specialties')
    op.drop_index(op.f('ix_resources_title'), table_name='resources')
    op.drop_table('resources')
    # ### end Alembic commands ###
